### ISSUE TITLE
Implement new style designs

### ISSUE THREAD

**Issue by seanperkins** [MobilityLabs/pdredesign-client#297]

**Comment by MakotoTheKnight** [comment]
@rickymetz In all likelihood we'll be merging the client with the server.  Does this task still apply to the client or would we be better served capturing it in the server project?

**Comment by rickymetz** [comment]
@MakotoTheKnight Can we mark this as done, and opt to capture style issues in a more granular way? Otherwise this task may never be done.

**Comment by MakotoTheKnight** [comment]
Sounds fine to me.  We can close it out on this side.
